In [3]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv('movies_metadata.csv')

In [5]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [6]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

In [8]:
df.shape

(45466, 24)

In [9]:
df.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

In [10]:
df = df.drop_duplicates().reset_index(drop=True)

In [11]:
df=df[['title','overview','genres','tagline','vote_average','popularity']]

In [12]:
df

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...","[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,"[{'id': 35, 'name': 'Comedy'}]",Just When His World Is Back To Normal... He's ...,5.7,8.387519
...,...,...,...,...,...,...
45448,Subdue,Rising and falling between a man and woman.,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",Rising and falling between a man and woman,4.0,0.072051
45449,Century of Birthing,An artist struggles to finish his work while a...,"[{'id': 18, 'name': 'Drama'}]",NaN,9.0,0.178241
45450,Betrayal,"When one of her hits goes wrong, a professiona...","[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",A deadly game of wits.,3.8,0.903007
45451,Satan Triumphant,"In a small town live two brothers, one a minis...",[],NaN,0.0,0.003503
45452,Queerama,50 years after decriminalisation of homosexual...,[],NaN,0.0,0.163015

In [13]:
df.isnull().sum()

title               6
overview          954
genres              0
tagline         25045
vote_average        6
popularity          5
dtype: int64

In [14]:
df = df.dropna(subset = ['title'])

In [15]:
df['overview'] = df['overview'].fillna('')

In [16]:
df.iloc[0]['genres']
import ast

In [17]:
df['genres'] = df['genres'].apply(lambda x: " ".join([i['name'] for i in ast.literal_eval(x)]))

In [18]:
df.head()

,title,overview,genres,tagline,vote_average,popularity
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,NaN,7.7,21.946943
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519

In [19]:
df['tagline'] = df['tagline'].fillna('')

In [20]:
df.isnull().sum()

title           0
overview        0
genres          0
tagline         0
vote_average    0
popularity      0
dtype: int64

In [21]:
df['tags'] = df['overview'] + " " + df['genres'] + " " + df['tagline']

In [22]:
df.head()

,title,overview,genres,tagline,vote_average,popularity,tags
0,Toy Story,"Led by Woody, Andy's toys live happily in his ...",Animation Comedy Family,,7.7,21.946943,"Led by Woody, Andy's toys live happily in his ..."
1,Jumanji,When siblings Judy and Peter discover an encha...,Adventure Fantasy Family,Roll the dice and unleash the excitement!,6.9,17.015539,When siblings Judy and Peter discover an encha...
2,Grumpier Old Men,A family wedding reignites the ancient feud be...,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,6.5,11.7129,A family wedding reignites the ancient feud be...
3,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",Comedy Drama Romance,Friends are the people who let you be yourself...,6.1,3.859495,"Cheated on, mistreated and stepped on, the wom..."
4,Father of the Bride Part II,Just when George Banks has recovered from his ...,Comedy,Just When His World Is Back To Normal... He's ...,5.7,8.387519,Just when George Banks has recovered from his ...

In [23]:
df['tags'][2]

"A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming the locals who worry she'll scare the fish away. But she's less interested in seafood than she is in cooking up a hot time with Max. Romance Comedy Still Yelling. Still Fighting. Still Ready for Love."

In [24]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import re

In [25]:
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

True

In [26]:
stop_words = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [27]:
def preprocess_text(text):
  text = str(text).lower()
  text = re.sub(r'[^a-zA-Z0-9\s]', '', text)

  words = text.split()
  words = [word for word in words if word not in stop_words]

  words = [lemmatizer.lemmatize(word) for word in words]
  return " ".join(words)

In [28]:
df['tags'] = df['tags'].apply(preprocess_text)

In [29]:
df['tags'][2]

'family wedding reignites ancient feud nextdoor neighbor fishing buddy john max meanwhile sultry italian divorce open restaurant local bait shop alarming local worry shell scare fish away shes less interested seafood cooking hot time max romance comedy still yelling still fighting still ready love'

In [30]:
df = df.reset_index(drop = True)

In [31]:
indices = pd.Series(df.index, index = df['title']).drop_duplicates()
indices

title
Toy Story                          0
Jumanji                            1
Grumpier Old Men                   2
Waiting to Exhale                  3
Father of the Bride Part II        4
                               ...
Subdue                         45442
Century of Birthing            45443
Betrayal                       45444
Satan Triumphant               45445
Queerama                       45446
Length: 45447, dtype: int64

In [32]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [33]:
tfidf = TfidfVectorizer(max_features= 50000,ngram_range = (1,2),stop_words = 'english')

In [34]:
tfidf_matrix = tfidf.fit_transform(df['tags'])

In [35]:
tfidf_matrix

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1555864 stored elements and shape (45447, 50000)>

In [36]:
from sklearn.metrics.pairwise import cosine_similarity

In [37]:
def recommend(title, n = 10):
  if title not in indices:
    return ['Movie Not Found']

  idx = indices[title]
  sim_score = cosine_similarity(tfidf_matrix[idx], tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]
  return df['title'].iloc[similar_idx]

In [38]:
recommend('Avatar')

26547                                      Avatar 2
13883                          The Inhabited Island
26553                                Thor: Ragnarok
28633                          Stand by Me Doraemon
43431                        Moontrap: Target Earth
2457                                     The Matrix
6414     Lara Croft Tomb Raider: The Cradle of Life
21567                The Secret of the Third Planet
14119                          The Three Musketeers
9949                             A Trip to the Moon
Name: title, dtype: object

In [39]:
import pickle
pickle.dump(tfidf_matrix,open('tfidf_matrix.pkl','wb'))
pickle.dump(indices,open('indices.pkl','wb'))
df.to_pickle('df.pkl')
pickle.dump(recommend,open('recommend.pkl','wb'))

In [44]:
import pandas as pd
df = pd.read_csv('movies_metadata.csv')
print(df['id']) # Replace 'id' with the actual column name

0           862
1          8844
2         15602
3         31357
4         11862
          ...
45461    439050
45462    111109
45463     67758
45464    227506
45465    461257
Name: id, Length: 45466, dtype: object

In [45]:
ids_list = df['id'].tolist()
print(ids_list)

['862', '8844', '15602', '31357', '11862', '949', '11860', '45325', '9091', '710', '9087', '12110', '21032', '10858', '1408', '524', '4584', '5', '9273', '11517', '8012', '1710', '9691', '12665', '451', '16420', '9263', '17015', '902', '37557', '9909', '63', '78802', '9598', '47018', '687', '139405', '33689', '9603', '34615', '31174', '11443', '35196', '9312', '577', '11861', '807', '10530', '8391', '629', '117164', '11448', '49133', '26441', '97406', '124057', '9089', '11010', '99040', '11359', '17182', '2054', '10607', '19760', '9536', '11525', '40628', '4482', '10634', '755', '11859', '28387', '48750', '20927', '36929', '9102', '124626', '27526', '9623', '46785', '400', '880', '146599', '188588', '8447', '10534', '17414', '13997', '2086', '61548', '9095', '12158', '9283', '9208', '40154', '406', '45549', '63076', '11062', '13685', '47475', '2045', '9614', '688', '11907', '10874', '89333', '96357', '197', '103', '33542', '43566', '71754', '43612', '51352', '16934', '10324', '78406', '55731', '32119', '11066', '11104', '37975', '2074', '27793', '44284', '290157', '110972', '32622', '73067', '11863', '55475', '124636', '9101', '123360', '5757', '39428', '124639', '9302', '11000', '249882', '16388', '9737', '30765', '10474', '22279', '30157', '568', '11780', '34996', '414', '649', '1873', '5894', '1775', '8839', '20649', '10329', '8963', '26564', '8068', '8512', '1572', '13552', '259209', '6520', '9073', '10428', '17447', '9886', '9482', '19326', '9344', '9071', '8973', '15730', '47608', '2293', '9070', '68274', '48787', '34574', '1642', '11472', '36196', '11980', '58372', '32646', '10533', '56088', '10802', '10149', '18402', '9348', '139408', '281', '5967', '79593', '47939', '36834', '9090', '3512', '52856', '77350', '9560', '9804', '31611', '65796', '49805', '26258', '50797', '19155', '76', '11017', '37141', '9382', '6715', '18256', '22625', '2292', '1909', '8984', '61813', '4954', '62488', '10531', '11929', '8467', '10451', '20156', '18395', '522', '397', '10525', '27985', '15789', '27303', '21183', '10954', '47867', '43475', '72031', '14275', '1024', '17207', '13701', '14819', '32631', '11777', '628', '87729', '18713', '6280', '9061', '37108', '6071', '11', '9587', '19101', '49980', '17961', '18183', '4476', '11008', '47504', '32325', '43742', '28313', '11318', '3036', '40490', '24070', '8986', '10510', '17402', '38722', '8438', '11593', '1945', '39310', '109560', '56428', '63105', '131957', '241', '9058', '527', '18220', '6950', '101', '63020', '2307', '680', '41478', '25296', '40156', '11450', '30304', '10452', '12106', '161495', '3586', '110', '108', '109', '159185', '36357', '92769', '28033', '22586', '14334', '2636', '2164', '11395', '278', '9905', '87078', '12527', '20306', '36614', '27993', '31439', '9067', '9059', '193', '25066', '46797', '12122', '11381', '32636', '36141', '95963', '1587', '9271', '2064', '19855', '60855', '236', '48287', '3049', '2759', '12635', '10497', '11382', '9331', '10731', '10464', '34152', '9495', '29973', '888', '13', '712', '16295', '48992', '10879', '10660', '10714', '41647', '8587', '1689', '11596', '854', '9359', '23333', '36593', '12280', '2788', '10427', '11011', '49803', '8987', '1637', '15128', '8831', '36955', '10449', '10395', '12160', '40480', '52038', '29444', '26352', '39953', '41580', '315', '22067', '18242', '11667', '32502', '267188', '28732', '75555', '42981', '278939', '291731', '226229', '203119', '172923', '316098', '8011', '171857', '2654', '18069', '19092', '2758', '38129', '10436', '13595', '46094', '9409', '11853', '16771', '46924', '11041', '306', '14522', '26203', '178', '19819', '57834', '4722', '18215', '1607', '26391', '117553', '6075', '11310', '18658', '9350', '9612', '2124', '26261', '19176', '49299', '11566', '9571', '9739', '24257', '34444', '26141', '10997', '50463', '10443', '20239', '16297', '18551', '25440', '9024', '37233', '1634', '13815', '5503', '35588', '2087', '41579', '18620', '41006', '4916', '2019', '31642', '9255', '26271', '10612', '2259', '16097', '11934', '106143', '12475', '9386', '7984', '59930', '15765', '31643', '6', '329', '10909', '507', '34024', '29918', '9593', '42580', '22317', '1413', '12121', '2246', '10502', '10440', '9516', '2320', '5879', '83718', '11971', '2625', '31911', '788', '21450', '11231', '41588', '10447', '31586', '9300', '9559', '9800', '713', '8291', '18133', '25557', '22588', '10872', '1245', '11858', '7007', '10467', '5550', '8005', '2088', '10412', '47889', '14534', '56583', '41878', '424', '35233', '14291', '103413', '11236', '11592', '8850', '10445', '695', '43535', '12519', '23210', '858', '867', '78', '13203', '10442', '11074', '33367', '9607', '17585', '9057', '20967', '10635', '9479', '10057', '11969', '41590', '319', '26408', '15139', '161158', '218473', '85247', '11446', '51980', '24405', '11655', '11800', '8223', '14587', '31504', '41653', '53185', '95743', '23637', '17600', '10897', '349394', '21352', '68806', '37345', '32562', '47507', '25403', '124304', '9066', '771', '251', '812', '280', '581', '80350', '268', '274', '408', '10020', '10895', '114', '41043', '576', '15477', '59146', '124472', '30528', '7300', '10824', '261246', '275', '25059', '11827', '8766', '23570', '47333', '54850', '51242', '10112', '4307', '46029', '32308', '88893', '52873', '123505', '340210', '44281', '28121', '12520', '1592', '166901', '36447', '19042', '38884', '47449', '36259', '41852', '40926', '9099', '2021', '61752', '10988', '11479', '398959', '287305', '339428', '12652', '10684', '954', '68445', '18989', '10801', '54285', '8840', '278978', '124625', '11107', '16417', '70934', '10363', '161070', '10539', '10543', '18414', '47502', '11902', '27098', '25087', '5801', '896', '3065', '318177', '2300', '8069', '288173', '187851', '27768', '221917', '8072', '35797', '88030', '185191', '83857', '33245', '124460', '27281', '105045', '40001', '29621', '117730', '20762', '37144', '48260', '12656', '38867', '277270', '25969', '44103', '753', '43634', '9103', '90214', '29649', '10990', '8866', '12233', '23449', '36355', '37667', '90148', '922', '11876', '52633', '62364', '11687', '9304', '73183', '131232', '9100', '20759', '46063', '365371', '32513', '40651', '36915', '40507', '9802', '25697', '21588', '664', '11867', '47119', '314352', '9323', '10280', '10535', '124613', '532', '26744', '16299', '10547', '245268', '935', '55613', '215107', '41007', '35645', '110465', '255546', '40751', '275096', '85778', '11101', '9826', '9879', '63564', '22621', '7095', '26890', '46732', '124633', '202425', '196940', '77771', '181083', '41225', '188589', '87190', '627', '32872', '602', '14553', '9566', '10545', '9894', '11543', '9268', '52059', '9327', '123763', '81949', '42005', '124306', '183955', '44535', '44495', '78285', '11228', '10779', '26748', '38223', '9294', '49963', '11363', '1645', '31546', '77056', '36344', '18550', '11511', '172198', '34170', '281085', '109478', '124645', '12606', '69895', '35206', '151489', '4837', '12632', '9098', '282919', '124614', '18975', '11962', '2925', '28628', '3595', '9308', '92381', '18555', '12123', '10830', '3573', '10546', '18862', '31417', '9431', '124619', '297645', '48144', '46986', '144982', '47907', '10061', '36266', '549', '10478', '66634', '116690', '213917', '145925', '100914', '238', '159', '11134', '88224', '132641', '42758', '9303', '23945', '37820', '22479', '9054', '241058', '11985', '10232', '59569', '410921', '38955', '110513', '114089', '11015', '9306', '12559', '58770', '124851', '3587', '10723', '56077', '19004', '101230', '253632', '10987', '44705', '20318', '43596', '79782', '26933', '27854', '981', '872', '2769', '13320', '164', '426', '567', '3078', '13528', '28288', '213', '284', '239', '4808', '289', '963', '11113', '6620', '804', '26531', '909', '630', '770', '31044', '599', '15', '62', '121357', '705', '22490', '223', '25670', '303', '4174', '8356', '381', '20758', '29376', '1859', '18299', '17281', '64382', '10907', '32093', '1939', '22292', '3598', '3080', '198', '13562', '1712', '220', '3529', '3085', '2897', '1585', '3083', '900', '43795', '85638', '50001', '43905', '22688', '23114', '26378', '40206', '22356', '260', '43488', '22613', '10331', '488', '22733', '261', '57575', '32574', '22657', '76464', '22649', '176841', '125587', '39448', '52855', '39940', '172868', '85328', '124632', '11076', '63945', '58985', '890', '10861', '1770', '44465', '2033', '18203', '9333', '47260', '9400', '9401', '12241', '25739', '161806', '11306', '9625', '10680', '6346', '18660', '35115', '14821', '14136', '10869', '22660', '19186', '31102', '6878', '15944', '18444', '20723', '173', '864', '24795', '11224', '81310', '15947', '9078', '29682', '8367', '433', '11360', '11114', '12335', '12092', '10948', '11229', '15121', '562', '10163', '48862', '117036', '47199', '11159', '9591', '30500', '41843', '55058', '10938', '11412', '10586', '42314', '27845', '108365', '23223', '49471', '38153', '25147', '9716', '43777', '454', '10218', '819', '38191', '56830', '11238', '27256', '31530', '66473', '28120', '1834', '26282', '37218', '252', '116356', '16372', '11561', '11302', '623', '583', '12614', '21711', '11575', '475', '11331', '521', '21202', '88', '500', '792', '8491', '402', '10537', '11386', '9504', '15764', '601', '67365', '25842', '2119', '744', '136311', '221', '702', '25750', '17642', '427043', '146341', '9305', '37616', '11112', '21612', '141210', '102461', '36998', '200383', '116844', '1630', '26626', '124837', '11816', '11843', '10379', '2756', '790', '1103', '11298', '4480', '4481', '49688', '10765', '762', '44497', '85588', '278621', '99479', '55049', '124829', '79306', '356054', '10548', '531', '104931', '4483', '18919', '31556', '26167', '26174', '61461', '117500', '218713', '217802', '127973', '659', '30892', '86369', '8074', '124676', '38554', '49763', '41326', '36555', '10608', '11216', '7452', '64567', '892', '1600', '26561', '975', '18129', '54405', '150823', '409', '38251', '10161', '1412', '41768', '10409', '14285', '2469', '10174', '31225', '510', '11455', '1891', '2493', '85', '68', '679', '429', '13446', '389', '947', '185', '595', '28', '335', '1892', '144', '1092', '769', '348', '766', '175', '11645', '10835', '539', '525', '240', '600', '530', '10705', '279', '3109', '311', '1578', '703', '9549', '1398', '387', '9277', '343', '37291', '490', '11235', '218', '763', '9665', '18971', '696', '379', '207', '37247', '1480', '9322', '826', '422', '829', '828', '3090', '9964', '3063', '13667', '694', '235', '832', '765', '5925', '11778', '4485', '137', '33', '982', '8428', '212', '105', '1633', '11202', '1554', '149', '8009', '903', '11673', '3034', '339', '10404', '914', '756', '288', '910', '2640', '16633', '665', '11031', '11314', '15143', '89', '10322', '783', '10644', '11257', '14370', '12104', '625', '8816', '830', '2323', '983', '642', '655', '10341', '639', '266022', '168450', '30180', '31388', '41801', '66034', '348138', '96288', '61536', '18762', '331367', '8077', '814', '41671', '27214', '52263', '33519', '16235', '11449', '41848', '25944', '24913', '49126', '32076', '571', '8851', '37843', '32146', '30346', '6114', '229', '13549', '9529', '1598', '11349', '7340', '6217', '377', '653', '28198', '794', '31640', '8744', '25189', '145', '2212', '199', '7863', '12498', '9279', '53234', '17204', '21539', '85589', '12709', '20539', '11674', '199512', '64900', '1573', '152', '174', '172', '154', '157', '168', '364', '11967', '9086', '621', '9037', '10173', '55687', '168535', '8845', '46681', '578', '579', '17692', '17795', '75', '13891', '9390', '378', '10896', '2322', '41240', '26949', '9819', '49799', '31908', '46027', '3179', '1802', '4232', '9361', '2928', '30285', '10549', '58102', '18451', '27265', '49935', '8818', '36758', '36040', '74239', '9415', '55146', '303693', '12145', '42424', '34314', '2892', '9404', '85242', '9622', '8860', '197537', '66597', '14832', '9619', '40506', '31000', '4104', '26306', '203829', '43775', '14908', '784', '12489', '168283', '16448', '55936', '17894', '28059', '58911', '17949', '1968', '61563', '66', '20735', '11419', '333165', '25796', '638', '25624', '9366', '60083', '21915', '90928', '50091', '18420', '19952', '9446', '28005', '9403', '27322', '10003', '9311', '11844', '884', '49806', '1624', '88423', '16052', '4477', '24662', '18423', '76996', '6499', '50512', '9405', '12723', '9360', '9434', '118991', '21626', '13982', '93946', '77223', '31465', '12793', '102878', '105763', '9611', '47694', '10357', '9977', '816', '2163', '124680', '16399', '124843', '31017', '24645', '49478', '12499', '18', '68545', '1811', '109614', '60082', '105045', '53023', '64802', '11239', '50850', '15321', '2058', '9450', '125021', '330', '38523', '16375', '33660', '59232', '45671', '17770', '15170', '1701', '201445', '26422', '124642', '1639', '49235', '106129', '291634', '107743', '415', '47686', '65889', '11103', '11970', '34941', '407992', '8874', '17991', '11956', '266', '754', '37567', '43771', '124834', '249358', '111367', '607', '18080', '38225', '17834', '686', '65046', '4421', '9387', '10603', '2142', '8413', '10336', '20737', '9413', '14585', '18519', '49462', '8834', '9458', '8854', '38295', '22073', '37244', '4961', '9416', '26180', '17832', '9772', '6072', '1669', '468', '32519', '108401', '10806', '9433', '6623', '2118', '978', '9437', '29461', '56651', '10351', '66588', '2649', '14289', '10155', '75250', '20457', '18355', '33657', '55306', '68924', '36434', '2255', '28353', '9427', '172545', '17589', '3597', '1813', '36797', '12628', '33344', '25099', '45019', '63437', '62422', '782', '29911', '9827', '1959', '251481', '8067', '125052', '45153', '10871', '14398', '10890', '99002', '1281', '32332', '9770', '12616', '34838', '14905', '14583', '11975', '4995', '9281', '45928', '563', '61337', '19931', '31535', '10215', '9823', '37165', '45609', '38904', '45565', '9407', '4824', '9444', '9414', '8078', '29938', '11831', '2895', '39177', '19601', '124606', '42832', '22797', '2639', '9574', '10371', '489', '167738', '293820', '9714', '102406', '170430', '8197', '6283', '279698', '49728', '64562', '4233', '191874', '10217', '438108', '597', '714', '52537', '12799', '62394', '9922', '547', '25994', '184', '9746', '9438', '115', '26941', '27103', '9410', '32302', '216794', '88863', '154821', '41417', '12538', '586', '2666', '46338', '54007', '11258', '9490', '9411', '25719', '9033', '11220', '21253', '6116', '9457', '281289', '43911', '39424', '44361', '11702', '2923', '12238', '11568', '41577', '66894', '11003', '10153', '49645', '47112', '102732', '30949', '2898', '9558', '83593', '320011', '26269', '11808', '6970', '47452', '18205', '36943', '21736', '17941', '10668', '9313', '42807', '617', '36568', '37272', '5910', '9440', '53092', '32911', '44308', '124821', '32456', '93350', '62695', '32144', '17127', '40688', '17133', '19848', '17644', '1774', '30265', '2157', '70581', '8838', '29193', '795', '16980', '27472', '47881', '9469', '12488', '98499', '81367', '267', '16148', '21252', '73135', '9449', '6264', '90414', '188870', '215373', '78149', '15513', '31220', '13907', '29825', '10622', '30020', '17139', '34582', '10216', '9771', '24560', '76330', '9448', '38618', '18316', '78373', '77514', '49474', '4415', '39467', '55561', '8656', '209345', '58680', '35161', '35796', '18937', '929', '9452', '1878', '9844', '40505', '14342', '9715', '26610', '20064', '40961', '1965', '312', '6068', '15037', '50043', '37636', '17044', '60951', '21334', '416437', '32284', '51955', '37410', '47481', '53765', '10674', '136134', '846', '12655', '3050', '1389', '11020', '20862', '108548', '9464', '95', '944', '35680', '11551', '473', '102304', '544', '10513', '28966', '65203', '143', '42861', '33680', '56164', '12311', '43277', '43278', '34106', '43266', '27367', '17661', '28580', '887', '33667', '23383', '25430', '27191', '11426', '654', '15919', '1725', '5769', '874', '10633', '17917', '3116', '1051', '1366', '12102', '16619', '9443', '11050', '606', '746', '380', '403', '11485', '466', '13820', '15389', '13597', '2108', '10014', '10072', '10131', '10160', '11284', '4488', '9725', '9728', '9730', '9731', '10225', '10281', '10283', '948', '11281', '10676', '11357', '11361', '36599', '39929', '41828', '41769', '10585', '11186', '11187', '609', '11133', '10306', '9552', '11586', '11587', '941', '942', '943', '927', '928', '9340', '9342', '38509', '60033', '12101', '19', '165', '196', '551', '16084', '17984', '22328', '32611', '3170', '346', '859', '841', '11051', '242', '1411', '9769', '9424', '9835', '857', '17539', '44322', '22777', '20173', '10957', '9570', '16249', '13962', '14612', '19378', '65157', '29228', '19379', '11164', '18887', '40866', '24736', '10122', '24816', '9994', '25445', '12129', '14140', '10439', '11158', '9354', '28736', '34774', '37969', '9631', '9820', '14013', '36606', '96196', '98505', '1779', '10849', '678', '907', '5961', '47908', '42121', '2887', '11974', '20348', '26648', '11911', '793', '35144', '9325', '43037', '10340', '10144', '10414', '10437', '15300', '12230', '13380', '10693', '11335', '11135', '11319', '14822', '15969', '13155', '10249', '15943', '10882', '24808', '19762', '13850', '2619', '65158', '53565', '41841', '27332', '97', '10419', '11675', '2107', '6471', '9442', '11591', '13697', '19158', '227', '87', '123', '9314', '11336', '9980', '10657', '10489', '10823', '11497', '2907', '9454', '8688', '118452', '16155', '48894', '23954', '12761', '396', '14367', '11814', '16081', '18331', '15171', '11837', '11704', '11639', '4978', '10380', '11976', '15144', '11522', '11557', '13853', '11415', '37530', '8393', '11937', '21661', '9320', '33644', '14662', '125124', '115872', '39930', '10692', '805', '34584', '34636', '2182', '28070', '77469', '10278', '36647', '17915', '14557', '9417', '41469', '19381', '34637', '4011', '161795', '1580', '5854', '573', '2370', '5780', '506', '22527', '574', '11219', '30159', '845', '1978', '3682', '51942', '46702', '54795', '46748', '847', '117', '14577', '37498', '38621', '59138', '28047', '4175', '31667', '13321', '21734', '31997', '24197', '11462', '31995', '940', '2762', '12684', '2761', '8208', '52907', '15007', '36049', '52748', '75793', '47695', '31930', '20213', '543', '36054', '143750', '52782', '36055', '36056', '2760', '64398', '10220', '431', '31641', '223318', '69848', '22796', '22256', '37550', '37916', '21873', '21500', '84116', '12626', '37818', '3525', '129628', '2321', '2028', '16384', '91217', '77314', '10699', '11597', '218624', '47947', '48311', '44772', '14347', '41090', '18282', '18169', '11082', '5971', '11933', '20096', '30815', '881', '4478', '22318', '53113', '2109', '122289', '24746', '72987', '193103', '8195', '9877', '26618', '21132', '11855', '24016', '14785', '14794', '3486', '11071', '1091', '10403', '11337', '162', '25723', '73351', '8916', '28134', '9429', '12159', '27791', '43106', '30197', '10156', '10377', '3121', '4975', '37532', '9713', '134368', '85837', '1039', '9821', '4437', '1890', '1955', '39437', '11932', '6435', '108316', '10683', '63709', '9445', '2657', '9425', '32326', '637', '8675', '125762', '20701', '9945', '73', '18603', '46889', '12888', '3033', '9882', '10663', '4518', '1808', '3600', '17037', '297', '5332', '21589', '8336', '11893', '123056', '12223', '32081', '14924', '10002', '41817', '19426', '12560', '9798', '14444', '9487', '9466', '666', '2042', '10162', '309', '692', '24018', '1678', '39256', '1680', '244', '10730', '31947', '8130', '11532', '9749', '14628', '9626', '13698', '10466', '707', '11954', '9336', '10157', '12118', '10587', '11825', '11895', '9447', '12257', '37536', '10029', '27104', '11252', '8545', '10223', '9745', '200', '9837', '11545', '1934', '110643', '11881', '13764', '24951', '8879', '1369', '1368', '1370', '10303', '9326', '10328', '11285', '1367', '1371', '1374', '1375', '15196', '11904', '215875', '15596', '13818', '29968', '44326', '1885', '8856', '10495', '5825', '9489', '16885', '76857', '8741', '9276', '9822', '39314', '10312', '9441', '9422', '125582', '24525', '10368', '11365', '140897', 

In [46]:
print(df['id'].to_string(index=False))

       862
      8844
     15602
     31357
     11862
       949
     11860
     45325
      9091
       710
      9087
     12110
     21032
     10858
      1408
       524
      4584
         5
      9273
     11517
      8012
      1710
      9691
     12665
       451
     16420
      9263
     17015
       902
     37557
      9909
        63
     78802
      9598
     47018
       687
    139405
     33689
      9603
     34615
     31174
     11443
     35196
      9312
       577
     11861
       807
     10530
      8391
       629
    117164
     11448
     49133
     26441
     97406
    124057
      9089
     11010
     99040
     11359
     17182
      2054
     10607
     19760
      9536
     11525
     40628
      4482
     10634
       755
     11859
     28387
     48750
     20927
     36929
      9102
    124626
     27526
      9623
     46785
       400
       880
    146599
    188588
      8447
     10534
     17414
     13997
      2086
     61548
      9095
     12158
      9283
      9208
     40154
       406
     45549
     63076
     11062
     13685
     47475
      2045
      9614
       688
     11907
     10874
     89333
     96357
       197
       103
     33542
     43566
     71754
     43612
     51352
     16934
     10324
     78406
     55731
     32119
     11066
     11104
     37975
      2074
     27793
     44284
    290157
    110972
     32622
     73067
     11863
     55475
    124636
      9101
    123360
      5757
     39428
    124639
      9302
     11000
    249882
     16388
      9737
     30765
     10474
     22279
     30157
       568
     11780
     34996
       414
       649
      1873
      5894
      1775
      8839
     20649
     10329
      8963
     26564
      8068
      8512
      1572
     13552
    259209
      6520
      9073
     10428
     17447
      9886
      9482
     19326
      9344
      9071
      8973
     15730
     47608
      2293
      9070
     68274
     48787
     34574
      1642
     11472
     36196
     11980
     58372
     32646
     10533
     56088
     10802
     10149
     18402
      9348
    139408
       281
      5967
     79593
     47939
     36834
      9090
      3512
     52856
     77350
      9560
      9804
     31611
     65796
     49805
     26258
     50797
     19155
        76
     11017
     37141
      9382
      6715
     18256
     22625
      2292
      1909
      8984
     61813
      4954
     62488
     10531
     11929
      8467
     10451
     20156
     18395
       522
       397
     10525
     27985
     15789
     27303
     21183
     10954
     47867
     43475
     72031
     14275
      1024
     17207
     13701
     14819
     32631
     11777
       628
     87729
     18713
      6280
      9061
     37108
      6071
        11
      9587
     19101
     49980
     17961
     18183
      4476
     11008
     47504
     32325
     43742
     28313
     11318
      3036
     40490
     24070
      8986
     10510
     17402
     38722
      8438
     11593
      1945
     39310
    109560
     56428
     63105
    131957
       241
      9058
       527
     18220
      6950
       101
     63020
      2307
       680
     41478
     25296
     40156
     11450
     30304
     10452
     12106
    161495
      3586
       110
       108
       109
    159185
     36357
     92769
     28033
     22586
     14334
      2636
      2164
     11395
       278
      9905
     87078
     12527
     20306
     36614
     27993
     31439
      9067
      9059
       193
     25066
     46797
     12122
     11381
     32636
     36141
     95963
      1587
      9271
      2064
     19855
     60855
       236
     48287
      3049
      2759
     12635
     10497
     11382
      9331
     10731
     10464
     34152
      9495
     29973
       888
        13
       712
     16295
     48992
     10879
     10660
     10714
     41647
      8587
      1689
     11596
       854
      9359
     23333
     36593
     12280
      2788
     10427
     11011
     49803
      8987
      1637
     15128
      8831
     36955
     10449
     10395
     12160
     40480
     52038
     29444
     26352
     39953
     41580
       315
     22067
     18242
     11667
     32502
    267188
     28732
     75555
     42981
    278939
    291731
    226229
    203119
    172923
    316098
      8011
    171857
      2654
     18069
     19092
      2758
     38129
     10436
     13595
     46094
      9409
     11853
     16771
     46924
     11041
       306
     14522
     26203
       178
     19819
     57834
      4722
     18215
      1607
     26391
    117553
      6075
     11310
     18658
      9350
      9612
      2124
     26261
     19176
     49299
     11566
      9571
      9739
     24257
     34444
     26141
     10997
     50463
     10443
     20239
     16297
     18551
     25440
      9024
     37233
      1634
     13815
      5503
     35588
      2087
     41579
     18620
     41006
      4916
      2019
     31642
      9255
     26271
     10612
      2259
     16097
     11934
    106143
     12475
      9386
      7984
     59930
     15765
     31643
         6
       329
     10909
       507
     34024
     29918
      9593
     42580
     22317
      1413
     12121
      2246
     10502
     10440
      9516
      2320
      5879
     83718
     11971
      2625
     31911
       788
     21450
     11231
     41588
     10447
     31586
      9300
      9559
      9800
       713
      8291
     18133
     25557
     22588
     10872
      1245
     11858
      7007
     10467
      5550
      8005
      2088
     10412
     47889
     14534
     56583
     41878
       424
     35233
     14291
    103413
     11236
     11592
      8850
     10445
       695
     43535
     12519
     23210
       858
       867
        78
     13203
     10442
     11074
     33367
      9607
     17585
      9057
     20967
     10635
      9479
     10057
     11969
     41590
       319
     26408
     15139
    161158
    218473
     85247
     11446
     51980
     24405
     11655
     11800
      8223
     14587
     31504
     41653
     53185
     95743
     23637
     17600
     10897
    349394
     21352
     68806
     37345
     32562
     47507
     25403
    124304
      9066
       771
       251
       812
       280
       581
     80350
       268
       274
       408
     10020
     10895
       114
     41043
       576
     15477
     59146
    124472
     30528
      7300
     10824
    261246
       275
     25059
     11827
      8766
     23570
     47333
     54850
     51242
     10112
      4307
     46029
     32308
     88893
     52873
    123505
    340210
     44281
     28121
     12520
      1592
    166901
     36447
     19042
     38884
     47449
     36259
     41852
     40926
      9099
      2021
     61752
     10988
     11479
    398959
    287305
    339428
     12652
     10684
       954
     68445
     18989
     10801
     54285
      8840
    278978
    124625
     11107
     16417
     70934
     10363
    161070
     10539
     10543
     18414
     47502
     11902
     27098
     25087
      5801
       896
      3065
    318177
      2300
      8069
    288173
    187851
     27768
    221917
      8072
     35797
     88030
    185191
     83857
     33245
    124460
     27281
    105045
     40001
     29621
    117730
     20762
     37144
     48260
     12656
     38867
    277270
     25969
     44103
       753
     43634
      9103
     90214
     29649
     10990
      8866
     12233
     23449
     36355
     37667
     90148
       922
     11876
     52633
     62364
     11687
      9304
     73183
    131232
      9100
     20759
     46063
    365371
     32513
     40651
     36915
     40507
      9802
     25697
     21588
       664
     11867
     47119
    314352
      9323
     10280
     10535
    124613
       532
     26744
     16299
     10547
    245268
       935
     55613
    215107
     41007
     35645
    110465
    255546
     40751
    275096
     85778
     11101
      9826
      9879
     63564
     22621
      7095
     26890
     46732
    124633
    202425
    196940
     77771
    181083
     41225
    188589
     87190
       627
     32872
       602
     14553
      9566
     10545
      9894
     11543
      9268
     52059
      9327
    123763
     81949
     42005
    124306
    183955
     44535
     44495
     78285
     11228
     10779
     26748
     38223
      9294
     49963
     11363
      1645
     31546
     77056
     36344
     18550
     11511
    172198
     34170
    281085
    109478
    124645
     12606
     69895
     35206
    151489
      4837
     12632
      9098
    282919
    124614
     18975
     11962
      2925
     28628
      3595
      9308
     92381
     18555
     12123
     10830
      3573
     10546
     18862
     31417
      9431
    124619
    297645
     48144
     46986
    144982
     47907
     10061
     36266
       549
     10478
     66634
    116690
    213917
    145925
    100914
       238
       159
     11134
     88224
    132641
     42758
      9303
     23945
     37820
     22479
      9054
    241058
     11985
     10232
     59569
    410921
     38955
    110513
    114089
     11015
      9306
     12559
     58770
    124851
      3587
     10723
     56077
     19004
    101230
    253632
     10987
     44705
     20318
     43596
     79782
     26933
     27854
       981
       872
      2769
     13320
       164
       426
       567
      3078
     13528
     28288
       213
       284
       239
      4808
       289
       963
     11113
      6620
       804
     26531
       909
       630
       770
     31044
       599
        15
        62
    121357
       705
     22490
       223
     25670
       303
      4174
      8356
       381
     20758
     29376
      1859
     18299
     17281
     64382
     10907
     32093
      1939
     22292
      3598
      3080
       198
     13562
      1712
       220
      3529
      3085
      2897
      1585
      3083
       900
     43795
     85638
     50001
     43905
     22688
     23114
     26378
     40206
     22356
       260
     43488
     22613
     10331
       488
     22733
       261
     57575
     32574
     22657
     76464
     22649
    176841
    125587
     39448
     52855
     39940
    172868
     85328
    124632
     11076
     63945
     58985
       890
     10861
      1770
     44465
      2033
     18203
      9333
     47260
      9400
      9401
     12241
     25739
    161806
     11306
      9625
     10680
      6346
     18660
     35115
     14821
     14136
     10869
     22660
     19186
     31102
      6878
     15944
     18444
     20723
       173
       864
     24795
     11224
     81310
     15947
      9078
     29682
      8367
       433
     11360
     11114
     12335
     12092
     10948
     11229
     15121
       562
     10163
     48862
    117036
     47199
     11159
      9591
     30500
     41843
     55058
     10938
     11412
     10586
     42314
     27845
    108365
     23223
     49471
     38153
     25147
      9716
     43777
       454
     10218
       819
     38191
     56830
     11238
     27256
     31530
     66473
     28120
      1834
     26282
     37218
       252
    116356
     16372
     11561
     11302
       623
       583
     12614
     21711
     11575
       475
     11331
       521
     21202
        88
       500
       792
      8491
       402
     10537
     11386
      9504
     15764
       601
     67365
     25842
      2119
       744
    136311
       221
       702
     25750
     17642
    427043
    146341
      9305
     37616
     11112
     21612
    141210
    102461
     36998
    200383
    116844
      1630
     26626
    124837
     11816
     11843
     10379
      2756
       790
      1103
     11298
      4480
      4481
     49688
     10765
       762
     44497
     85588
    278621
     99479
     55049
    124829
     79306
    356054
     10548
       531
    104931
      4483
     18919
     31556
     26167
     26174
     61461
    117500
    218713
    217802
    127973
       659
     30892
     86369
      8074
    124676
     38554
     49763
     41326
     36555
     10608
     11216
      7452
     64567
       892
      1600
     26561
       975
     18129
     54405
    150823
       409
     38251
     10161
      1412
     41768
     10409
     14285
      2469
     10174
     31225
       510
     11455
      1891
      2493
        85
        68
       679
       429
     13446
       389
       947
       185
       595
        28
       335
      1892
       144
      1092
       769
       348
       766
       175
     11645
     10835
       539
       525
       240
       600
       530
     10705
       279
      3109
       311
      1578
       703
      9549
      1398
       387
      9277
       343
     37291
       490
     11235
       218
       763
      9665
     18971
       696
       379
       207
     37247
      1480
      9322
       826
       422
       829
       828
      3090
      9964
      3063
     13667
       694
       235
       832
       765
      5925
     11778
      4485
       137
        33
       982
      8428
       212
       105
      1633
     11202
      1554
       149
      8009
       903
     11673
      3034
       339
     10404
       914
       756
       288
       910
      2640
     16633
       665
     11031
     11314
     15143
        89
     10322
       783
     10644
     11257
     14370
     12104
       625
      8816
       830
      2323
       983
       642
       655
     10341
       639
    266022
    168450
     30180
     31388
     41801
     66034
    348138
     96288
     61536
     18762
    331367
      8077
       814
     41671
     27214
     52263
     33519
     16235
     11449
     41848
     25944
     24913
     49126
     32076
       571
      8851
     37843
     32146
     30346
      6114
       229
     13549
      9529
      1598
     11349
      7340
      6217
       377
       653
     28198
       794
     31640
      8744
     25189
       145
      2212
       199
      7863
     12498
      9279
     53234
     17204
     21539
     85589
     12709
     20539
     11674
    199512
     64900
      1573
       152
       174
       172
       154
       157
       168
       364
     11967
      9086
       621
      9037
     10173
     55687
    168535
      8845
     46681
       578
       579
     17692
     17795
        75
     13891
      9390
       378
     10896
      2322
     41240
     26949
      9819
     49799
     31908
     46027
      3179
      1802
      4232
      9361
      2928
     30285
     10549
     58102
     18451
     27265
     49935
      8818
     36758
     36040
     74239
      9415
     55146
    303693
     12145
     42424
     34314
      2892
      9404
     85242
      9622
      8860
    197537
     66597
     14832
      9619
     40506
     31000
      4104
     26306
    203829
     43775
     14908
       784
     12489
    168283
     16448
     55936
     17894
     28059
     58911
     17949
      1968
     61563
        66
     20735
     11419
    333165
     25796
       638
     25624
      9366
     60083
     21915
     90928
     50091
     18420
     19952
      9446
     28005
      9403
     27322
     10003
      9311
     11844
       884
     49806
      1624
     88423
     16052
      4477
     24662
     18423
     76996
      6499
     50512
      9405
     12723
      9360
      9434
    118991
     21626
     13982
     93946
     77223
     31465
     12793
    102878
    105763
      9611
     47694
     10357
      9977
       816
      2163
    124680
     16399
    124843
     31017
     24645
     49478
     12499
        18
     68545
      1811
    109614
     60082
    105045
     53023
     64802
     11239
     50850
     15321
      2058
      9450
    125021
       330
     38523
     16375
     33660
     59232
     45671
     17770
     15170
      1701
    201445
     26422
    124642
      1639
     49235
    106129
    291634
    107743
       415
     47686
     65889
     11103
     11970
     34941
    407992
      8874
     17991
     11956
       266
       754
     37567
     43771
    124834
    249358
    111367
       607
     18080
     38225
     17834
       686
     65046
      4421
      9387
     10603
      2142
      8413
     10336
     20737
      9413
     14585
     18519
     49462
      8834
      9458
      8854
     38295
     22073
     37244
      4961
      9416
     26180
     17832
      9772
      6072
      1669
       468
     32519
    108401
     10806
      9433
      6623
      2118
       978
      9437
     29461
     56651
     10351
     66588
      2649
     14289
     10155
     75250
     20457
     18355
     33657
     55306
     68924
     36434
      2255
     28353
      9427
    172545
     17589
      3597
      1813
     36797
     12628
     33344
     25099
     45019
     63437
     62422
       782
     29911
      9827
      1959
    251481
      8067
    125052
     45153
     10871
     14398
     10890
     99002
      1281
     32332
      9770
     12616
     34838
     14905
     14583
     11975
      4995
      9281
     45928
       563
     61337
     19931
     31535
     10215
      9823
     37165
     45609
     38904
     45565
      9407
      4824
      9444
      9414
      8078
     29938
     11831
      2895
     39177
     19601
    124606
     42832
     22797
      2639
      9574
     10371
       489
    167738
    293820
      9714
    102406
    170430
      8197
      6283
    279698
     49728
     64562
      4233
    191874
     10217
    438108
       597
       714
     52537
     12799
     62394
      9922
       547
     25994
       184
      9746
      9438
       115
     26941
     27103
      9410
     32302
    216794
     88863
    154821
     41417
     12538
       586
      2666
     46338
     54007
     11258
      9490
      9411
     25719
      9033
     11220
     21253
      6116
      9457
    281289
     43911
     39424
     44361
     11702
      2923
     12238
     11568
     41577
     66894
     11003
     10153
     49645
     47112
    102732
     30949
      2898
      9558
     83593
    320011
     26269
     11808
      6970
     47452
     18205
     36943
     21736
     17941
     10668
      9313
     42807
       617
     36568
     37272
      5910
      9440
     53092
     32911
     44308
    124821
     32456
     93350
     62695
     32144
     17127
     40688
     17133
     19848
     17644
      1774
     30265
      2157
     70581
      8838
     29193
       795
     16980
     27472
     47881
      9469
     12488
     98499
     81367
       267
     16148
     21252
     73135
      9449
      6264
     90414
    188870
    215373
     78149
     15513
     31220
     13907
     29825
     10622
     30020
     17139
     34582
     10216
      9771
     24560
     76330
      9448
     38618
     18316
     78373
     77514
     49474
      4415
     39467
     55561
      8656
    209345
     58680
     35161
     35796
     18937
       929
      9452
      1878
      9844
     40505
     14342
      9715
     26610
     20064
     40961
      1965
       312
      6068
     15037
     50043
     37636
     17044
     60951
     21334
    416437
     32284
     51955
     37410
     47481
     53765
     10674
    136134
       846
     12655
      3050
      1389
     11020
     20862
    108548
      9464
        95
       944
     35680
     11551
       473
    102304
       544
     10513
     28966
     65203